config/routes.rb
SampleApp::Application.routes.draw do
  root to: "static_pages#home"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :account_confirmations, only: [:new, :edit]
  resources :signup_form, only: [:new, :create]
  resources :conversations do
    resources :posts do
    end
  end
  resources :posts, only: [:new, :index, :create]
  resources :profiles
  
  match '/help',      to: 'static_pages#help'
  match '/about',     to: 'static_pages#about'
  match '/contact',   to: 'static_pages#contact'
  
  match '/signup',    to: 'users#new',         via: 'get'    # Signup page
  match '/signup',    to: 'users#new',         via: 'post'   # Homepage signup form
  match '/signin',    to: 'sessions#new',      via: 'get'
  match '/signout',   to: 'sessions#destroy',  via: 'delete'

  match '/new_conversation', to: 'conversations#new', via: 'get'

end

app/models/conversation.rb
# == Schema Information
#
# Table name: conversations
#
#  id            :integer          not null, primary key
#  title         :string(255)      not null
#  person_id     :integer          not null
#  first_post_id :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Conversation < ActiveRecord::Base

	# -- ASSOCIATIONS
	belongs_to :starter, class_name: "Person", foreign_key: "person_id"

	has_many :posts

	# -- VALIDATIONS
	validates :title, presence: true, length: { maximum: 140 }

	def setup_first_post
		self.posts.build(person_id: self.starter.id)
	end

	def set_first_post(post_id)
		self.first_post_id = post_id
		self.save!
	end

	def most_recent_post(post)
		self.posts.index(post) + 1
	end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

	before_filter :signed_in_user, only: [:new, :create]
	before_filter :current_person, only: [:new, :create]

	def index
		@conversations = Conversation.all
	end

	def new
		@conversation = ConversationForm.new(current_person)
	end

	def create
		@conversation = ConversationForm.new(current_person)
		if @conversation.submit(convo_params, post_params)
			redirect_to conversation_path(@conversation.conversation)
		else
			render 'new'
		end
	end

	def show
		begin
			@conversation = Conversation.find(params[:id])
		rescue
			redirect_to root_url
		end
	end

	private

	def convo_params
		params.require(:conversation).permit(:title)
	end

	def post_params
		params.require(:conversation).permit(:content)
	end
end

app/helpers/conversations_helper.rb
module ConversationsHelper

	def persist_conversation(post)
		@conversation ||= post.conversation
	end

end

app/views/conversations/index.html.erb
<% @conversations.each do |conversation| %>
	<div>
		<h3><%= conversation.title %></h3>
	</div>
<% end %>

app/views/conversations/new.html.erb
<% provide(:title, 'Start a conversation!') %>
<section class="static-wrapper">
	<div class="form-header">
		<span class="call-to-action-dynamic">
			Start a new conversation
		</span>
	</div>
	<%= form_for @conversation, url: conversations_path do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		<%= render 'conversations/partials/fields', f: f %>
	<% end %>
</section>

app/views/conversations/show.html.erb
<%= render 'conversations/partials/title' %>

<section class="responses" id="responses">
	<% @conversation.posts.each do |post| %>
		<% present post do |presenter| %>
			<%= render 'conversations/partials/post', post: post, presenter: presenter %>
		<% end %>
	<% end %>
</section>

<div id="reply_post"></div> 