config/routes.rb
SampleApp::Application.routes.draw do
  root to: "static_pages#home"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :account_confirmations, only: [:new, :edit]
  resources :signup_form, only: [:new, :create]
  resources :conversations do
    resources :posts do
    end
  end
  resources :posts, only: [:new, :index, :create]
  resources :profiles
  
  match '/help',      to: 'static_pages#help'
  match '/about',     to: 'static_pages#about'
  match '/contact',   to: 'static_pages#contact'
  
  match '/signup',    to: 'users#new',         via: 'get'    # Signup page
  match '/signup',    to: 'users#new',         via: 'post'   # Homepage signup form
  match '/signin',    to: 'sessions#new',      via: 'get'
  match '/signout',   to: 'sessions#destroy',  via: 'delete'

  match '/new_conversation', to: 'conversations#new', via: 'get'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home 
  	unless signed_in?
      @static_page_form = StaticPageForm.new
  	end 
  end

  def help
  end

  def about
  end

  def contact
  end
    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/homepage/_homepage_buttons.html.erb
<div class="buttons">
	<%= link_to "Sign up", signup_path, class: "button signup-button" %>
	<%= link_to "Sign in", signin_path, class: "button signin-button" %>
</div>

app/views/static_pages/homepage/_homepage_fakebottom.html.erb
<div class="fakebottom-row">
	<a class="fakebottom-item" href="#">Search Kshizzy</a>
  	<a class="fakebottom-item" href="#">Browse our library</a>
  	<a class="fakebottom-item" href="#">What's Kshizzy all about?</a>
  	<a class="fakebottom-item" href="#">What our users are saying</a>
</div>

app/views/static_pages/homepage/_homepage_signin_button.html.erb
<%= link_to "Sign in", signin_path, class: "button signin-button" %>

app/views/static_pages/homepage/_homepage_signin_form.html.erb
<div class="well signin-form">
	<%= form_for( @static_page_form, url: sessions_path ) do |f| %>
		<%= f.text_field :email, placeholder: "Email" %>
		<%= f.password_field :password, placeholder: "Password" %>
		<%= f.submit "Sign in", class: "btn btn-info btn-large", style: "float:right" %>
	<% end %>
	<small class="pull-left"><%= link_to "Forgot password?", new_password_reset_path %></small>
</div>

app/views/static_pages/homepage/_homepage_signup_button.html.erb
<%= link_to "Sign up", signup_path, class: "button signup-button" %>

app/views/static_pages/homepage/_homepage_signup_form.html.erb
<div class="well signup-form">
	<h4>New to Kshizzy? Sign up.</h4>
	<%= form_for( @static_page_form, 
				  url: signup_path, 
				  method: 'post' ) do |f| %>		
		<div class="row-fluid">	
			<%= f.text_field :first_name, 
							    placeholder: "First Name", 
								class: "span6" %>
			<%= f.text_field :last_name, 
								placeholder: "Last Name", 
								class: "span6" %>	
		</div>			
		<%= f.text_field :email, placeholder: "Email" %>
		<%= f.submit "Sign up for Kshizzy", 
						class: "btn btn-large btn-warning", 
						style: "float:right" %>
	<% end %>		
</div>

app/views/static_pages/homepage/_homepage_welcome_message.html.erb
<div class="welcome-message">
	<!-- <h1>kshizzy</h1> -->
	
	<!-- <h2>kshzz<span style="font-weight: bold;">y</span> is a connected learning platform that helps you build critical thinking skills</h2> -->
	
	<!-- <h2>What did you learn today?</h2> -->
	
	<!-- <h2>Explore your interests and insights with friends and colleagues around the world.</h2> -->
	
	<!-- <h2>Kshizzy is a connected learning platform that helps you explore your interests and insights with anyone around the world.</h2> -->

	<h1>Welcome to kshzz<span style="font-weight: bold;">y</span></h1>
<!-- 	<h2>Collaborate, learn, and build critical thinking skills with family, friends, and colleagues around the world</h2> -->
	<h2>kshizzy helps you learn, collaborate, and build critical thinking skills</h2>
</div>