config/routes.rb
SampleApp::Application.routes.draw do
  root to: "static_pages#home"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :account_confirmations, only: [:new, :edit]
  resources :signup_form, only: [:new, :create]
  resources :conversations do
    resources :posts do
    end
  end
  resources :posts, only: [:new, :index, :create]
  resources :profiles
  
  match '/help',      to: 'static_pages#help'
  match '/about',     to: 'static_pages#about'
  match '/contact',   to: 'static_pages#contact'
  
  match '/signup',    to: 'users#new',         via: 'get'    # Signup page
  match '/signup',    to: 'users#new',         via: 'post'   # Homepage signup form
  match '/signin',    to: 'sessions#new',      via: 'get'
  match '/signout',   to: 'sessions#destroy',  via: 'delete'

  match '/new_conversation', to: 'conversations#new', via: 'get'

end

app/views/layouts/popout/_popout-body.html.erb
<div class="popout-body">
	<div class="popout-bucket">
		<%= gravatar_for @current_user, size: 60 %>
		<div class="bucket-content">
			<h5><%= link_to current_user.person.first_name, "#" %><h5>
		</div>	
	</div>
	<div class="popout-carousel">
		<%= render 'layouts/popout/popout_carousel_notifications' %>
		<%= render 'layouts/popout/popout_carousel_ideas' %>
		<%= render 'layouts/popout/popout_carousel_people' %>
		<%= render 'layouts/popout/popout_carousel_actions' %>
		<%= render 'layouts/popout/popout_carousel_messages' %>
		<%= render 'layouts/popout/popout_carousel_conversations' %>
		<%= render 'layouts/popout/popout_carousel_settings' %>
	</div>
</div>

app/views/layouts/popout/_popout-footer.html.erb
<div class="popout-footer center ">
	<%= link_to "Sign out", signout_path, method: "delete",
		'data-disable-with' => "Signing out..." %>
</div>	

app/views/layouts/popout/_popout-header.html.erb
<div class="popout-header">
	<div class="icon" id="popout-toggle"></div>
</div>

app/views/layouts/popout/_popout.html.erb
<section class="popout">
	<%= render 'layouts/popout/popout-header' %>
	<%= render 'layouts/popout/popout-body' %>
	<%= render 'layouts/popout/popout-footer' %>
</section>

app/views/layouts/popout/_popout_carosel_actions.html.erb
<div class="carousel-actions">		
	<div class="carousel-action" id="action-ppl">
		<div class="action-wrapper">
			<div class="icon" id="icon-ppl"></div>
			<div class="type">People</div>
		</div>
		<div class="content-wrapper">
			<section id="deleteME" style="display:none; background-color: white;">
				<p>This will fade in after</p>
				<p>Following</p>
				<p>Followers</p>
				<p>Recomended</p>
			</section>
		</div>
	</div>
	<div class="carousel-action" id="action-msg">
		<div class="action-wrapper">
			<div class="icon" id="icon-msg"></div>
			<div class="type">Messages</div>
		</div>
	</div>
	<div class="carousel-action" id="action-thk">
		<div class="action-wrapper">
			<div class="icon" id="icon-thk"></div>
			<div class="type">Ideas</div>
		</div>
	</div>
	<div class="carousel-action" id="action-con">
		<div class="action-wrapper">
			<div class="icon" id="icon-con"></div>
			<div class="type">Conversations</div>
		</div>
	</div>
	<div class="carousel-action" id="action-not">
		<div class="action-wrapper">
			<div class="icon" id="icon-not"></div>
			<div class="type">Notifications</div>
		</div>
	</div>
	<div class="carousel-action" id="action-mng">
		<div class="action-wrapper">
			<div class="icon" id="icon-mng"></div>
			<div class="type">Settings</div>
		</div>
	</div>				
</div>

app/views/layouts/popout/_popout_carosel_content.html.erb
<div class="carousel-content" style="background-color: #333333;">
	<div>
		<p style="color: white;"><< Go back</p>
	</div>		
</div>

app/views/layouts/popout/_popout_carousel_actions.html.erb
<div class="carousel-actions">		
	<div class="carousel-action carousel-action-left" id="action-people">
		<div class="action-wrapper">
			<div class="icon" id="icon-ppl"></div>
			<div class="type">People</div>
		</div>
		<div class="content-wrapper">
		</div>
	</div>
	<div class="carousel-action carousel-action-right" id="action-messages">
		<div class="action-wrapper">
			<div class="icon" id="icon-msg"></div>
			<div class="type">Messages</div>
		</div>
	</div>
	<div class="carousel-action carousel-action-left" id="action-ideas">
		<div class="action-wrapper">
			<div class="icon" id="icon-thk"></div>
			<div class="type">Ideas</div>
		</div>
	</div>
	<div class="carousel-action carousel-action-right" id="action-conversations">
		<div class="action-wrapper">
			<div class="icon" id="icon-con"></div>
			<div class="type">Conversations</div>
		</div>
	</div>
	<div class="carousel-action carousel-action-left" id="action-notifications">
		<div class="action-wrapper">
			<div class="icon" id="icon-not"></div>
			<div class="type">Notifications</div>
		</div>
	</div>
	<div class="carousel-action carousel-action-right" id="action-settings">
		<div class="action-wrapper">
			<div class="icon" id="icon-mng"></div>
			<div class="type">Settings</div>
		</div>
	</div>				
</div>

app/views/layouts/popout/_popout_carousel_conversations.html.erb
<div class="carousel carousel-conversations carousel-right" id="carousel-conversations">
	<div>
		<p style="color: white;"><< Go back</p>
	</div>	
	<p><%= link_to "Start new conversation", new_conversation_path %></p>	
</div>

app/views/layouts/popout/_popout_carousel_ideas.html.erb
<div class="carousel carousel-ideas carousel-left" id="carousel-ideas">
	<div>
		<p style="color: white;"><< Go back</p>
	</div>		
</div>

app/views/layouts/popout/_popout_carousel_messages.html.erb
<div class="carousel carousel-messages carousel-right" id="carousel-messages">
	<div>
		<p style="color: white;"><< Go back</p>
	</div>		
</div>

app/views/layouts/popout/_popout_carousel_notifications.html.erb
<div class="carousel carousel-notifications carousel-left" id="carousel-notifications">
	<div>
		<p style="color: white;"><< Go back</p>
	</div>		
</div>

app/views/layouts/popout/_popout_carousel_people.html.erb
<div class="carousel carousel-people carousel-left" id="carousel-people">
	<div>
		<p style="color: white;"><< Go back</p>
	</div>		
</div>

app/views/layouts/popout/_popout_carousel_settings.html.erb
<div class="carousel carousel-settings carousel-right" id="carousel-settings">
	<div>
		<p style="color: white;"><< Go back</p>
	</div>		
</div>